<?php

namespace Database\Seeders;

use App\Models\Guru;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Guru::create([
            'mata_pelajaran_id' => 1,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "123",
            'username' => "123",
            'password' => Hash::make("123"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 2,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "234",
            'username' => "234",
            'password' => Hash::make("234"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 3,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "345",
            'username' => "345",
            'password' => Hash::make("345"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 4,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "456",
            'username' => "456",
            'password' => Hash::make("456"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 5,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "567",
            'username' => "567",
            'password' => Hash::make("567"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 6,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "678",
            'username' => "678",
            'password' => Hash::make("678"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 7,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "789",
            'username' => "789",
            'password' => Hash::make("789"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 8,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "890",
            'username' => "890",
            'password' => Hash::make("890"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 9,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => "321",
            'username' => "321",
            'password' => Hash::make("321"),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 10,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '432',
            'username' => '432',
            'password' => Hash::make('432'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 11,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '543',
            'username' => '543',
            'password' => Hash::make('543'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 12,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '654',
            'username' => '654',
            'password' => Hash::make('654'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 13,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '765',
            'username' => '765',
            'password' => Hash::make('765'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 14,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '876',
            'username' => '876',
            'password' => Hash::make('876'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 15,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '987',
            'username' => '987',
            'password' => Hash::make('987'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 16,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '1234',
            'username' => '1234',
            'password' => Hash::make('1234'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 17,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '2345',
            'username' => '2345',
            'password' => Hash::make('2345'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 18,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '3456',
            'username' => '3456',
            'password' => Hash::make('3456'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 19,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '4567',
            'username' => '4567',
            'password' => Hash::make('4567'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 20,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '5678',
            'username' => '5678',
            'password' => Hash::make('5678'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
        Guru::create([
            'mata_pelajaran_id' => 21,
            'nama' => Str::random(10),
            'jabatan' => 'guru',
            'nomor_induk_yayasan' => '6789',
            'username' => '6789',
            'password' => Hash::make('6789'),
            'jenis_kelamin' => '-',
            'tempat_tanggal_lahir' => '-',
            'alamat' => '-',
            'pendidikan_terakhir' => '-',
            'no_hp' => '-',
            'profil' => '-',
            'ktp' => '-',
            'ijazah' => '-',
            'kartu_keluarga' => '-',
        ]);
    }
}
