name: 🚀 Deploy Website Production
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy website
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      # sync files via FTP
      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_MAIN }}
          username: ${{ secrets.FTP_USERNAME_MAIN }}
          password: ${{ secrets.FTP_PASSWORD_MAIN }}
          log-level: verbose           # Enable detailed logging
          server-dir: /remote-dir      # Specify the remote directory (update if necessary)
          local-dir: ./local-dir       # Specify the local directory (update if necessary)
          keep-alive: true             # Enable keep-alive functionality
          keep-alive-interval: 300     # Send keep-alive messages every 300 seconds (5 minutes)
